# Generated by Django 2.2.3 on 2019-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='hey',
            field=models.IntegerField(default=2),
        ),
    ]
