# Generated by Django 2.2.3 on 2019-07-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_foo_hey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foo',
            name='hey',
        ),
    ]
