# Generated by Django 2.2.3 on 2019-07-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.IntegerField(default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
