# Generated by Django 2.2.3 on 2019-07-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190729_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
        migrations.DeleteModel(
            name='Fooo',
        ),
    ]
